# Use the official Ubuntu image
FROM nginx:latest

# Set the working directory to root
WORKDIR /

# Copy custom web content to the Nginx server's default directory
COPY code/ /var/www/html
COPY code/ /usr/share/nginx/html

# Expose port 80 (default for Nginx)
EXPOSE 80

# Start Nginx in the foreground when the container starts
CMD ["nginx", "-g", "daemon off;"]
